openapi: "3.0.0"
paths:
  /dummy-response:
    get:
      responses:
        200:
          content:
            application/json:
              examples:
                dummy:
                  status: "GET ok"
    post:
      responses:
        201:
          content:
            application/json:
              examples:
                dummy:
                  status: "POST ok"
    put:
      responses:
        200:
          content:
            application/json:
              examples:
                dummy:
                  status: "PUT ok"
    patch:
      responses:
        200:
          content:
            application/json:
              examples:
                dummy:
                  status: "PATCH ok"
    delete:
      responses:
        200:
          content:
            application/json:
              examples:
                dummy:
                  status: "DELETE ok"
